### ISSUE TITLE
Support for Java 8

### ISSUE THREAD

**Issue by zhanif3** [HolmesProcessing/Holmes-Totem#11]
_From @webstergd on November 11, 2015 12:37_

We currently only support Java 7. We should add documentation to explain this. We should also discuss if we want to provide support for Java 8 in the future.

_Copied from original issue: HolmesProcessing/Holmes-Totem-old#11_

**Comment by zhanif3** [comment]
Currently enforced by build.sbt. We can rewrite the buildfile to reflect the usage of 8.

**Comment by webstergd** [comment]
updated version of akka and scala have resolved the java8 issue.
