### ISSUE TITLE
Should we provide a standard library of helper functions/vars

### ISSUE THREAD

**Issue by webstergd** [HolmesProcessing/Holmes-Totem#21]
Should we provide a shared standard library for Services? The library would include helper functions and variables that is useful for most Services. 

For example: 
1) variables for RE expressions to generate Tornado pages
2) object to help with storing temp files
3) class to override to provide Service meta information (name, version, date, etc)

**Comment by webstergd** [comment]
we also need a library to assist with submitting objects to storage

**Comment by ms-xy** [comment]
basic error class to provide a 400 error would be great
