### ISSUE TITLE
Default / page for information

### ISSUE THREAD

**Issue by webstergd** [HolmesProcessing/Holmes-Totem#22]
Should we provide a template for displaying Service Information? We could tie this into the shared library. 

Name:
Version: 
Description:
Copyright:
Config:

**Comment by zhanif3** [comment]
Yes, at the very least, each service should have an endpoint which self-identifies via a JSON block.

**Comment by webstergd** [comment]
I will work on a prototype with cvp.

**Comment by ms-xy** [comment]
Pull requests #69, #70, #71, and #72 fix this for the ZipMeta, Yara, PEInfo, and PeID services
