### ISSUE TITLE
ZipMeta: Support for files without central directory

### ISSUE THREAD

**Issue by ms-xy** [HolmesProcessing/Holmes-Totem#37]
Current behaviour:
In case of a corrupted central directory no results are generated for the files missing an entry there.
Further no checks are made to ensure all files were parsed.

Expected behaviour:
Not every valid zip file contains a central directory. (Files generated by the unix zip utility for example may lack these entirely)
For any entry missing in the central directory, the local directory should be used instead.

**Comment by webstergd** [comment]
closing the issue for now. We will need to research a better way for performing zip extractions.
