### ISSUE TITLE
Where should we place Docker files?

### ISSUE THREAD

**Issue by zhanif3** [HolmesProcessing/Holmes-Totem#4]
_From @webstergd on November 5, 2015 13:50_

Should this be a separate repository or contained in the service/[service_name] folder. 

_Copied from original issue: HolmesProcessing/Holmes-Totem-old#4_

**Comment by webstergd** [comment]
Looking at the VT Service I think we need to address this now. The current model works well for us but will cause an added level of confusion/work for anyone just trying to get started. As such, I vote for having each Service live in its own separate folder under service. 

In there we can add:
- README
- DEPENDENCY
- LICENCE
- Docker Container
- RESTful service
- service.scala
- watchguard.scala
- service.conf
- acl.conf

**Comment by webstergd** [comment]
docker files for services will be located in the service folder. Docker Compose configuration will be in the ~/config directory.
