### ISSUE TITLE
Clean up driver.conf zooWork

### ISSUE THREAD

**Issue by zhanif3** [HolmesProcessing/Holmes-Totem#5]
_From @webstergd on November 5, 2015 13:57_

Either comment the code to explain they are tests or add a flag. My vote is for flag

_Copied from original issue: HolmesProcessing/Holmes-Totem-old#5_

**Comment by zhanif3** [comment]
Flag will be added.

**Comment by webstergd** [comment]
A number of pull requests have effectively closed this.
