### ISSUE TITLE
RAM consumption when dealing with large results

### ISSUE THREAD

**Issue by cynexit** [HolmesProcessing/Holmes-Totem#53]
When Totem has to deal with many services which return large results (20MB - 100MB+) it starts to allocate lots and lots of memory until it gets killed by the OOM killer.
A service returning large results will get Totem to allocate more that 16GB in less than five minutes, we might want to look into this and see if there are any memory leaks, then try to optimize memory usage later down the road.

**Comment by webstergd** [comment]
closed in replace of #169
