### ISSUE TITLE
Metadata map field

### ISSUE THREAD

**Issue by zhanif3** [HolmesProcessing/Holmes-Totem#6]
_From @webstergd on November 5, 2015 14:8_

We need an ability to clearly push metadata through the system. from tasking to results so the DB planner can know how to properly handles the insertions. 

_Copied from original issue: HolmesProcessing/Holmes-Totem-old#6_

**Comment by zhanif3** [comment]
_From @cynexit on November 5, 2015 14:13_

Just as an example, here is the struct we send containing all the data cuckoo needs to push results back to CRTIs. This should be easily presentable as a map[string]string.

```
// critsData contains the most important data about a analysis handled
// by crits. This data is needed to conntect to crits and is present
// in every amqp message.
type CritsData struct {
    CritsURL   string `json:"crits_url"`
    AnalysisId string `json:"analysis_id"`
    ObjectType string `json:"object_type"`
    ObjectId   string `json:"object_id"`
    Username   string `json:"username"`
    ApiKey     string `json:"api_key"`
    MD5        string `json:"md5"`
    Source     string `json:"source"`
}
```

**Comment by zhanif3** [comment]
What does AnalysisID refer to here? Does it refer to a discrete service (Yara), or to the entire analytical job (running both Yara and Metadata, say)? If the former, this is a slightly larger burden. If the latter, I've got a branch that can correct this. 

Additionally, are any of those fields optional? We've got the option to strictly enforce or allow missing fields.

Finally, do we want to tack this onto the existing ZooWork, or create an entirely new message type?

**Comment by zhanif3** [comment]
_From @webstergd on November 8, 2015 20:37_

Analysis_ID is the tag used to identify the results from one Service that was run against an Object. So if you have a PE32 sample and run Distributed_Cuckoo in CRITs, it will create a unique MongoDB document identified by the Analysis_ID. This is a required field and used by the CRITs API to inform CRITs where to place the results. This will also be needed if you wish to modify the results directly though MongoDB. 

I assume we will potentially encounter this situation with other tools that we may wish to integrate with TOTEM. Thus, I vote for an optional tag in the TOTEM AMQP tasking to capture options that are requester specific. Then have TOTEM reattach the tag to the result message when it pushes it to the results queue. Storage will then be able to read these tags and figure out how to submit the results back to the Tasker. To state another way, we need this tag to pass through TOTEM to allow the Storage Planner to be able to submit the results back to the Tasker.  For example the tag will need to persist though the following work flow:
Tasking -> Tasking Queue -> TOTEM -> Results Tasking -> Storage -> Submit Back to Tasking

**Comment by zhanif3** [comment]
_From @webstergd on November 8, 2015 20:41_

Also, I would make this generic and not have TOTEM do any enforcement on what is entered in those fields. That check should be handled by a separate Gateway and rechecked again by Storage.

**Comment by zhanif3** [comment]
Sounds good. I'll implement as optional fields in a separate object - I'm comfortable with the Crits gateway managing the secondary fields.

**Comment by webstergd** [comment]
i think this is done
