### ISSUE TITLE
Improve generic watchdog functionality

### ISSUE THREAD

**Issue by zhanif3** [HolmesProcessing/Holmes-Totem#7]
_From @webstergd on November 5, 2015 14:11_

We need to improve the generic watchdog functionality. We need to monitor more then just restful calls. 

_Copied from original issue: HolmesProcessing/Holmes-Totem-old#7_

**Comment by webstergd** [comment]
This can be extended to provide support for waiting Services. For example, if we upload a file to virustotal we currently wait 5 minutes before rechecking the results. We could provide an HTTP code that is picked up by the Service's watchdog.scala. The watchdog then pushes the task to a waiting queue and  reruns. 

This would also be useful for services that require long queries like whois and potentially dynamic analysis.
