### ISSUE TITLE
PEInfo upgrade

### ISSUE THREAD

**Issue by zhanif3** [HolmesProcessing/Holmes-Totem#8]
_From @webstergd on November 6, 2015 12:56_

The current implementation of PEInfo is written with python. This causes potential performance hits when scaling. We should port the code over to GO and leverage the PE library [1]. Looks like all we would need to do is track offsets. 

[1] https://golang.org/pkg/debug/pe/ 

_Copied from original issue: HolmesProcessing/Holmes-Totem-old#8_

**Comment by zhanif3** [comment]
Frankly, this is a large alteration. We should consider having a separate repo made to maintain the (effectively) new pefile.

**Comment by webstergd** [comment]
I have Ma-Shell working on this. Right now the python version can take upwards of 50 seconds to execute. As pefile/peinfo is pretty standard, I will ask him to make this as an entirely new service.

**Comment by webstergd** [comment]
peinfo has some big errors maybe we should look at switching over to http://pev.sourceforge.net/

**Comment by webstergd** [comment]
I think it is time to create another parser based on pev over pefile. PEFile based analysis is just taking way to long. I am going to close this issue and create a new issue for creating a PEV based extractor.
